default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_bucket: <%= ENV["READINGNINJA_BUCKET"] %>
  aws_access: <%= ENV["READINGNINJA_ACCESS_KEY_ID"] %>
  aws_secret: <%= ENV["READINGNINJA_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["READINGNINJA_S3_REGION"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
